# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daq/DPGA/common

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daq/DPGA/common

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daq/DPGA/common/CMakeFiles /home/daq/DPGA/common/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daq/DPGA/common/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qcustomplot

# Build rule for target.
qcustomplot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qcustomplot
.PHONY : qcustomplot

# fast build rule for target.
qcustomplot/fast:
	$(MAKE) -f libqcustomplot/CMakeFiles/qcustomplot.dir/build.make libqcustomplot/CMakeFiles/qcustomplot.dir/build
.PHONY : qcustomplot/fast

#=============================================================================
# Target rules for targets named qcustomplot_automoc

# Build rule for target.
qcustomplot_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qcustomplot_automoc
.PHONY : qcustomplot_automoc

# fast build rule for target.
qcustomplot_automoc/fast:
	$(MAKE) -f libqcustomplot/CMakeFiles/qcustomplot_automoc.dir/build.make libqcustomplot/CMakeFiles/qcustomplot_automoc.dir/build
.PHONY : qcustomplot_automoc/fast

#=============================================================================
# Target rules for targets named ringshm

# Build rule for target.
ringshm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ringshm
.PHONY : ringshm

# fast build rule for target.
ringshm/fast:
	$(MAKE) -f libshm/CMakeFiles/ringshm.dir/build.make libshm/CMakeFiles/ringshm.dir/build
.PHONY : ringshm/fast

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) -f libframe/CMakeFiles/doc_doxygen.dir/build.make libframe/CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

#=============================================================================
# Target rules for targets named BuildEvent

# Build rule for target.
BuildEvent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BuildEvent
.PHONY : BuildEvent

# fast build rule for target.
BuildEvent/fast:
	$(MAKE) -f libframe/CMakeFiles/BuildEvent.dir/build.make libframe/CMakeFiles/BuildEvent.dir/build
.PHONY : BuildEvent/fast

#=============================================================================
# Target rules for targets named frame

# Build rule for target.
frame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frame
.PHONY : frame

# fast build rule for target.
frame/fast:
	$(MAKE) -f libframe/CMakeFiles/frame.dir/build.make libframe/CMakeFiles/frame.dir/build
.PHONY : frame/fast

#=============================================================================
# Target rules for targets named testframe

# Build rule for target.
testframe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testframe
.PHONY : testframe

# fast build rule for target.
testframe/fast:
	$(MAKE) -f libframe/CMakeFiles/testframe.dir/build.make libframe/CMakeFiles/testframe.dir/build
.PHONY : testframe/fast

#=============================================================================
# Target rules for targets named BuildEvent_Multi

# Build rule for target.
BuildEvent_Multi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BuildEvent_Multi
.PHONY : BuildEvent_Multi

# fast build rule for target.
BuildEvent_Multi/fast:
	$(MAKE) -f libframe/CMakeFiles/BuildEvent_Multi.dir/build.make libframe/CMakeFiles/BuildEvent_Multi.dir/build
.PHONY : BuildEvent_Multi/fast

#=============================================================================
# Target rules for targets named ReadEventBuild

# Build rule for target.
ReadEventBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReadEventBuild
.PHONY : ReadEventBuild

# fast build rule for target.
ReadEventBuild/fast:
	$(MAKE) -f libframe/CMakeFiles/ReadEventBuild.dir/build.make libframe/CMakeFiles/ReadEventBuild.dir/build
.PHONY : ReadEventBuild/fast

#=============================================================================
# Target rules for targets named daqdpga

# Build rule for target.
daqdpga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daqdpga
.PHONY : daqdpga

# fast build rule for target.
daqdpga/fast:
	$(MAKE) -f daqDpga/CMakeFiles/daqdpga.dir/build.make daqDpga/CMakeFiles/daqdpga.dir/build
.PHONY : daqdpga/fast

#=============================================================================
# Target rules for targets named visu

# Build rule for target.
visu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visu
.PHONY : visu

# fast build rule for target.
visu/fast:
	$(MAKE) -f visu/CMakeFiles/visu.dir/build.make visu/CMakeFiles/visu.dir/build
.PHONY : visu/fast

#=============================================================================
# Target rules for targets named visu_automoc

# Build rule for target.
visu_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visu_automoc
.PHONY : visu_automoc

# fast build rule for target.
visu_automoc/fast:
	$(MAKE) -f visu/CMakeFiles/visu_automoc.dir/build.make visu/CMakeFiles/visu_automoc.dir/build
.PHONY : visu_automoc/fast

#=============================================================================
# Target rules for targets named qtanalyse

# Build rule for target.
qtanalyse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtanalyse
.PHONY : qtanalyse

# fast build rule for target.
qtanalyse/fast:
	$(MAKE) -f QtAnalyses/CMakeFiles/qtanalyse.dir/build.make QtAnalyses/CMakeFiles/qtanalyse.dir/build
.PHONY : qtanalyse/fast

#=============================================================================
# Target rules for targets named qtanalyse_automoc

# Build rule for target.
qtanalyse_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtanalyse_automoc
.PHONY : qtanalyse_automoc

# fast build rule for target.
qtanalyse_automoc/fast:
	$(MAKE) -f QtAnalyses/CMakeFiles/qtanalyse_automoc.dir/build.make QtAnalyses/CMakeFiles/qtanalyse_automoc.dir/build
.PHONY : qtanalyse_automoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... qcustomplot"
	@echo "... qcustomplot_automoc"
	@echo "... ringshm"
	@echo "... doc_doxygen"
	@echo "... BuildEvent"
	@echo "... frame"
	@echo "... testframe"
	@echo "... BuildEvent_Multi"
	@echo "... ReadEventBuild"
	@echo "... daqdpga"
	@echo "... visu"
	@echo "... visu_automoc"
	@echo "... qtanalyse"
	@echo "... qtanalyse_automoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

